####
# ATTENTION:
# Replace all occurrences of jenkis with your project's name.
####

# v3 syntax
version: '3'

# Named volumes
volumes:
  # Postgres Data
  jenkis-postgres-data:
    driver: local

services:
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.4-nginx
    container_name: jenkis-app
    volumes:
      - .:/var/www/app
    ports:
      - "8181:8080"
      - "8083:8083"
    links:
      - postgres

  # Postgres (11)
  postgres:
    image: postgres:11
    container_name: jenkis-postgres
    volumes:
      - jenkis-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=jenkis
      - POSTGRES_DB=jenkis
      - POSTGRES_USER=jenkis
