version: '3'
volumes:
    jenkins_home:
      driver: local
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkis
    ports:
      - '9000:8080'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
    #   - '/var/run/docker.sock:/var/run/docker.sock'
