####
# ATTENTION:
# Replace all occurrences of sandbox with your project's name.
####

# v3 syntax
version: '3'

# Named volumes
volumes:
# Postgres Data
  postgres-data:
    driver: local


services:
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.3-nginx
    container_name: jenkis-nginx
    volumes:
      # Volumes entregueaki
      - .:/var/www/app
    ports:
      - "80:8080"
      - "443:8083"
    networks:
      - docker_jenkis

  # Postgres (11)
  postgres:
    image: postgres:11
    container_name: jenkis-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=jenkis
      - POSTGRES_USER=docker
    networks:
      - docker_jenkis
networks:
  docker_jenkis:
    driver: bridge

 




